(function(){
  "use strict";
  const K={bookings:"dinkside_bookings",blocked:"dinkside_blocked",rate:"dinkside_rate",password:"dinkside_admin_password"},DEFAULT_PASSWORD="CourtAdmin2026!",OPEN=7,CLOSE=27;
  const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  let section="overview",date=today();
  function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
  function addDays(d,n){const x=new Date(d+"T00:00:00Z");x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
  function dateObj(d){return new Date(d+"T00:00:00+08:00")} function formatDate(d){return new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeZone:"Asia/Manila"}).format(dateObj(d))}
  function hour(h){const n=h%24,s=n>=12?"PM":"AM";return`${n%12||12}:00 ${s}`} function money(n){return`₱${Number(n).toLocaleString("en-PH")}`}
  function bookings(){return read(K.bookings,[])} function saveBookings(v){write(K.bookings,v)} function blocked(){return read(K.blocked,[])} function saveBlocked(v){write(K.blocked,v)} function rate(){return Number(localStorage.getItem(K.rate)||350)}
  function escape(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  function rollover(){const now=Date.now(),cutoff=now-7*86400000;const list=bookings().map(b=>b.status==="confirmed"&&endTime(b)<=now?{...b,status:"completed",completed:new Date().toISOString()}:b).filter(b=>b.status!=="completed"||endTime(b)>cutoff);saveBookings(list)}
  function endTime(b){return dateObj(b.date).getTime()+b.end*3600000}
  function notify(message){const el=$("#admin-message");el.textContent=message;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),4000)}
  function showApp(){rollover();$("#admin-login").classList.add("hidden");$("#admin-app").classList.remove("hidden");renderNav();render()}
  function renderNav(){const items=[ ["overview","Overview"],["pending","Pending bookings"],["confirmed","Confirmed bookings"],["completed","Completed bookings"],["court","Court availability"],["pricing","Pricing"],["settings","Settings"] ];$("#admin-nav").innerHTML=items.map(([id,label])=>`<button data-section="${id}" class="${section===id?"active":""}">${label}</button>`).join("");document.querySelectorAll("[data-section]").forEach(b=>b.onclick=()=>{section=b.dataset.section;renderNav();render()})}
  function title(kicker,title,text){return`<div class="admin-title"><span>${kicker}</span><h1>${title}</h1><p>${text}</p></div>`}
  function render(){rollover();const root=$("#admin-content"),list=bookings();if(section==="overview")root.innerHTML=overview(list);if(["pending","confirmed","completed"].includes(section))root.innerHTML=bookingSection(list.filter(b=>b.status===section));if(section==="court")root.innerHTML=court();if(section==="pricing")root.innerHTML=pricing();if(section==="settings")root.innerHTML=settings();bind()}
  function overview(list){const todays=list.filter(b=>b.date===today()&&["pending","confirmed"].includes(b.status)),pending=list.filter(b=>b.status==="pending");return`${title("BOOKING OVERVIEW","Good day, Admin.","Here’s what’s happening with your court today.")}<div class="admin-stats"><article class="stat"><span>Today's bookings</span><strong>${todays.length}</strong><small>Pending and confirmed</small></article><article class="stat"><span>Confirmed today</span><strong>${todays.filter(b=>b.status==="confirmed").length}</strong><small>Reserved times</small></article><article class="stat"><span>Pending total</span><strong>${pending.length}</strong><small>Needs attention</small></article><article class="stat"><span>Hourly rate</span><strong>${money(rate())}</strong><small>Current public price</small></article></div><section class="admin-panel"><div class="admin-panel-head"><h2>Today’s schedule</h2></div>${todays.length?todays.map(bookingRow).join(""):'<p>No bookings today.</p>'}</section>`}
  function bookingSection(list){return`${title("BOOKING MANAGEMENT",section[0].toUpperCase()+section.slice(1)+" bookings",section==="completed"?"Finished reservations are kept for seven days, then deleted automatically.":"Review and manage court reservations.")}<section class="admin-panel">${list.length?list.map(bookingRow).join(""):`<p>No ${section} bookings.</p>`}</section>`}
  function bookingRow(b){return`<article class="admin-booking"><div><span class="status-pill ${b.status}">${b.status}</span><b>${escape(b.name)}</b><small>Mobile: ${escape(b.mobile)}</small><small>Booking: ${escape(b.reference)}</small></div><div><b>${formatDate(b.date)}</b><small>Court ${b.court||1} · ${hour(b.start)} – ${hour(b.end)} · ${b.hours}h</small></div><div><b>${money(b.total)}</b><small>${escape(b.payment)} · Ref: ${escape(b.transaction||"N/A")}</small></div><div class="admin-actions"><button data-view="${b.id}">View details</button>${b.status==="pending"?`<button data-status="confirmed" data-id="${b.id}">Confirm</button><button class="danger" data-status="rejected" data-id="${b.id}">Reject</button>`:""}${b.status==="confirmed"?`<button class="danger" data-status="cancelled" data-id="${b.id}">Cancel</button>`:""}</div></article>`}
  function statusAt(h,court){if(dateObj(date).getTime()+h*3600000<=Date.now())return"unavailable";const block=blocked().find(x=>x.date===date&&x.hour===h&&Number(x.court||1)===court);if(block)return block.status;const b=bookings().find(x=>x.date===date&&Number(x.court||1)===court&&["pending","confirmed"].includes(x.status)&&h>=x.start&&h<x.end);return b?(b.status==="confirmed"?"booked":"pending"):"available"}
  function adminCell(h,court){const s=statusAt(h,court),past=dateObj(date).getTime()+h*3600000<=Date.now();const actions=past?"<small>Past</small>":s==="available"?`<button class="secondary" data-slot="${h}" data-court-number="${court}" data-slot-status="unavailable">Close</button><button data-slot="${h}" data-court-number="${court}" data-slot-status="booked">Book</button>`:s==="unavailable"?`<button class="secondary" data-slot="${h}" data-court-number="${court}" data-slot-status="available">Reopen</button>`:s==="booked"?`<button class="danger" data-slot="${h}" data-court-number="${court}" data-slot-status="available">Cancel</button>`:"<small>Customer pending</small>";return`<div class="admin-court-cell ${s}"><b>${s}</b><div class="admin-actions-slot">${actions}</div></div>`}
  function court(){let rows="";for(let h=OPEN;h<CLOSE;h++)rows+=`<div class="admin-matrix-row"><div class="matrix-time"><strong>${hour(h)}</strong><small>${hour(h+1)}${h>=24?" · Next day":""}</small></div>${[1,2,3].map(c=>adminCell(h,c)).join("")}</div>`;const available=Array.from({length:CLOSE-OPEN},(_,i)=>OPEN+i).reduce((total,h)=>total+[1,2,3].filter(c=>statusAt(h,c)==="available").length,0);return`${title("COURT CONTROL","Court availability","View and manage all three courts for every time period.")}<div class="admin-control"><label>Schedule date <input id="admin-date" type="date" min="${today()}" value="${date}"></label><b>${available} court hours available</b></div><section class="admin-panel"><div class="admin-panel-head"><h2>All court schedules</h2><span>Asia/Manila</span></div><div class="admin-matrix"><div class="admin-matrix-head"><span>Time</span><span>Court 1</span><span>Court 2</span><span>Court 3</span></div>${rows}</div></section>`}
  function pricing(){return`${title("RATE MANAGEMENT","Pricing","Update the flat hourly rate shown across the booking website.")}<section class="admin-panel settings-panel"><label class="field">Hourly rate in Philippine pesos<input id="rate-input" type="number" min="1" value="${rate()}"></label><p>Current price: <b>${money(rate())} per court, per hour</b></p><button id="save-rate" class="lime-button">Update hourly rate</button></section>`}
  function settings(){return`${title("ADMINISTRATOR","Settings","Manage administrator access.")}<section class="admin-panel settings-panel"><h2>Reset password</h2><p>Changing the password signs out every other browser session.</p><dl><div><dt>Account</dt><dd>Portal Admin</dd></div><div><dt>Username</dt><dd>admin</dd></div></dl><form id="password-form" class="password-form"><label>Current password<input id="current-password" type="password" required></label><label>New password<input id="new-password" type="password" minlength="8" required></label><label>Confirm new password<input id="confirm-password" type="password" minlength="8" required></label><button class="lime-button">Reset password</button></form></section>`}
  function bind(){document.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>{const list=bookings(),item=list.find(x=>x.id===b.dataset.id);if(item){item.status=b.dataset.status;saveBookings(list);notify(`Booking ${item.status}.`);render()}});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>viewBooking(b.dataset.view));$("#admin-date")?.addEventListener("change",e=>{date=e.target.value;render()});document.querySelectorAll("[data-slot]").forEach(b=>b.onclick=()=>updateSlot(Number(b.dataset.slot),b.dataset.slotStatus,Number(b.dataset.courtNumber)));$("#save-rate")?.addEventListener("click",()=>{const n=Number($("#rate-input").value);if(n>0){localStorage.setItem(K.rate,String(Math.round(n)));notify("Hourly rate updated.");render()}});$("#password-form")?.addEventListener("submit",resetPassword)}
  function updateSlot(h,status,court){let blocks=blocked().filter(x=>!(x.date===date&&x.hour===h&&Number(x.court||1)===court));if(status!=="available")blocks.push({court,date,hour:h,status});else{const list=bookings(),item=list.find(x=>x.date===date&&Number(x.court||1)===court&&["pending","confirmed"].includes(x.status)&&h>=x.start&&h<x.end);if(item){item.status="cancelled";saveBookings(list)}}saveBlocked(blocks);notify(status==="available"?`Court ${court} hour reopened.`:`Court ${court} hour marked ${status}.`);render()}
  function viewBooking(id){const b=bookings().find(x=>x.id===id);if(!b)return;$("#detail-content").innerHTML=`<span class="eyebrow dark">BOOKING SUMMARY</span><h2>${escape(b.reference)}</h2><div class="admin-stats"><article class="stat"><span>Customer</span><b>${escape(b.name)}</b><small>${escape(b.mobile)}</small></article><article class="stat"><span>Schedule</span><b>${formatDate(b.date)}</b><small>Court ${b.court||1} · ${hour(b.start)} – ${hour(b.end)}</small></article><article class="stat"><span>Payment</span><b>${money(b.total)}</b><small>${escape(b.payment)} · ${escape(b.transaction||"N/A")}</small></article><article class="stat"><span>Status</span><b>${escape(b.status)}</b><small>${b.hours} hours</small></article></div><section class="admin-panel"><h3>Proof of payment</h3>${b.proofData?`<img class="proof-preview" src="${b.proofData}" alt="Payment proof">`:`<p>No preview stored. File name: ${escape(b.proofName||"N/A")}</p>`}</section>`;$("#detail-modal").classList.remove("hidden")}
  function resetPassword(e){e.preventDefault();const current=$("#current-password").value,next=$("#new-password").value,confirm=$("#confirm-password").value,stored=localStorage.getItem(K.password)||DEFAULT_PASSWORD;if(current!==stored){notify("Current password is incorrect.");return}if(next.length<8){notify("New password must contain at least 8 characters.");return}if(next!==confirm){notify("New passwords do not match.");return}localStorage.setItem(K.password,next);notify("Password reset successfully.");e.target.reset()}
  $("#login-form").addEventListener("submit",e=>{e.preventDefault();const valid=$("#admin-username").value.trim().toLowerCase()==="admin"&&$("#admin-password").value===(localStorage.getItem(K.password)||DEFAULT_PASSWORD);if(!valid){$("#login-error").textContent="Incorrect username or password.";$("#login-error").classList.remove("hidden");return}sessionStorage.setItem("dinkside_admin_session","1");showApp()});
  $("#logout").onclick=()=>{sessionStorage.removeItem("dinkside_admin_session");location.reload()};$("#close-detail").onclick=()=>$("#detail-modal").classList.add("hidden");$("#detail-modal").onmousedown=e=>{if(e.target.id==="detail-modal")e.currentTarget.classList.add("hidden")};
  if(sessionStorage.getItem("dinkside_admin_session")==="1")showApp();
  window.setInterval(()=>{if(section==="court"&&!$("#admin-app").classList.contains("hidden"))render()},60*1000);
})();

